# Generated by Django 5.2.6 on 2025-10-10 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Logical time of the event; client may supply; server uses now() if absent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Optional client/external id for deduplication', max_length=128, null=True)),
                ('visible', models.BooleanField(default=True, help_text='Soft visibility flag; set False to hide without deleting')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
    ]
