# Generated by Django 5.2.6 on 2025-10-01 13:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Logical time of the event; client may supply; server uses now() if absent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Optional client/external id for deduplication', max_length=128, null=True)),
                ('visible', models.BooleanField(default=True, help_text='Soft visibility flag; set False to hide without deleting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp', '-created_at'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='activities__user_id_4b25a0_idx'), models.Index(fields=['user', 'created_at'], name='activities__user_id_c5f267_idx'), models.Index(fields=['external_id'], name='activities__externa_f35130_idx')],
            },
        ),
    ]
