# Generated by Django 5.2.6 on 2025-10-03 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', '-timestamp'], name='activities__user_id_4b25a0_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'created_at'], name='activities__user_id_c5f267_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['external_id'], name='activities__externa_f35130_idx'),
        ),
    ]
