name: frontend_flutter
description: Interface Flutter pour l'authentification sécurisée avec Django backend.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  go_router: ^14.0.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.1.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  package_info_plus: ^4.0.0
  mime: ^1.0.2
  http_parser: ^4.0.0


services:
  web:
    environment:
      - FERNET_KEYS=["UkopL_QvrUhxcCRmupO4hXWM1pf0j2amYTHTUgTO3wA="]


  





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  image_picker_for_web: ^3.0.0


flutter:
  uses-material-design: true