# Generated by Django 5.2.6 on 2025-09-25 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('cin_numero', models.CharField(max_length=20, unique=True)),
                ('cin_date_delivrance', models.DateField()),
                ('situation_matrimoniale', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('veuf', 'Veuf(ve)'), ('divorce', 'Divorcé(e)')], max_length=20)),
                ('nombre_enfants', models.IntegerField(default=0)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_type', models.CharField(choices=[('general', 'Budget Général'), ('cfu', 'CFU'), ('etrangere', 'Etrangère')], max_length=20)),
                ('groupe_sanguin', models.CharField(max_length=5)),
                ('poste_precedent', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('autres_diplomes', models.TextField(blank=True)),
                ('observation', models.TextField(blank=True)),
                ('ref_affectation', models.CharField(max_length=100)),
                ('date_affectation', models.DateField()),
                ('date_entree_admin', models.DateField()),
                ('date_entree_hjra', models.DateField()),
                ('lieu_affectation', models.CharField(max_length=100)),
                ('conjoint_nom', models.CharField(blank=True, max_length=100)),
                ('conjoint_date_naiss', models.DateField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='manage_personnel.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(default='BFV', max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('organisme_code', models.CharField(max_length=20)),
                ('agency', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('rib_key', models.CharField(max_length=10)),
                ('bk_code', models.CharField(max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='manage_personnel.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='MfaTOTP',
        ),
    ]
