# Generated by Django 5.2.6 on 2025-10-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_mfa_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mfa_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_2fa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totp_secret',
        ),
    ]
