# Generated by Django 5.2.6 on 2025-09-25 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0002_profile_personnel_bankaccount_delete_mfatotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-created_at',), 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_mfa_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='agency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bk_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='organisme_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='rib_key',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_affectation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_entree_admin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_entree_hjra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='groupe_sanguin',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='lieu_affectation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='poste_precedent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='ref_affectation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='specialite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('profile', 'account_number')},
        ),
    ]
