# Generated by Django 5.2.6 on 2025-10-03 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0002_alter_profile_prefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts_legacy', to='manage_personnel.profile'),
        ),
    ]
