# Generated by Django 5.2.6 on 2025-10-04 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0003_alter_bankaccount_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='manage_personnel.profile'),
        ),
    ]
