# Generated by Django 5.2.6 on 2025-09-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0003_alter_bankaccount_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ('-id',)},
        ),
    ]
