# Generated by Django 5.2.6 on 2025-10-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0004_alter_bankaccount_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
