# Generated by Django 5.2.6 on 2025-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0004_alter_personnel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
