# Generated by Django 5.2.6 on 2025-09-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0005_alter_profile_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cin_date_delivrance',
            field=models.DateField(max_length=100),
        ),
    ]
