# Generated by Django 5.2.6 on 2025-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0005_delete_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Actif pour le service (auto/dé)activation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, help_text='Dernier accès connu', null=True),
        ),
    ]
