# Generated by Django 5.2.6 on 2025-09-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0006_alter_profile_cin_date_delivrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cin_date_delivrance',
            field=models.CharField(max_length=100),
        ),
    ]
