# Generated by Django 5.2.6 on 2025-09-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0007_alter_profile_cin_date_delivrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cin_numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
