# Generated by Django 5.2.6 on 2025-09-28 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0008_alter_profile_cin_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cin_date_delivrance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('veuf', 'Veuf(ve)'), ('divorce', 'Divorcé(e)')], max_length=20),
        ),
    ]
