# Generated by Django 5.2.6 on 2025-10-04 23:23

import bank_accounts.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_personnel', '0005_delete_bankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_code', models.CharField(blank=True, max_length=64, null=True)),
                ('agency', models.CharField(blank=True, max_length=64, null=True)),
                ('currency', models.CharField(blank=True, default='EUR', max_length=8)),
                ('iban_encrypted', bank_accounts.fields.EncryptedTextField(blank=True, null=True)),
                ('account_number_encrypted', bank_accounts.fields.EncryptedTextField(blank=True, null=True)),
                ('iban_normalized', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('masked_account', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('verification_metadata', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', related_query_name='bank_account', to='manage_personnel.profile')),
            ],
            options={
                'db_table': 'bank_account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=128)),
                ('target_type', models.CharField(blank=True, max_length=64, null=True)),
                ('target_id', models.CharField(blank=True, max_length=64, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_account_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('fee', 'Fee'), ('refund', 'Refund')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_accounts.bankaccount')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', related_query_name='bank_transaction', to='manage_personnel.profile')),
            ],
            options={
                'db_table': 'bank_transaction',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['profile'], name='bank_accoun_profile_7391fb_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['masked_account'], name='bank_accoun_masked__e8855f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['status'], name='bank_accoun_status_4669f3_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['iban_normalized'], name='bank_accoun_iban_no_8fa1ba_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaudit',
            index=models.Index(fields=['actor'], name='bank_accoun_actor_i_ca5dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaudit',
            index=models.Index(fields=['action'], name='bank_accoun_action_a41ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaudit',
            index=models.Index(fields=['target_type', 'target_id'], name='bank_accoun_target__c1144e_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaudit',
            index=models.Index(fields=['created_at'], name='bank_accoun_created_c250e1_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account'], name='bank_transa_bank_ac_2851a1_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['profile'], name='bank_transa_profile_25a672_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['timestamp'], name='bank_transa_timesta_5a1e5b_idx'),
        ),
    ]
