# Generated by Django 5.2.6 on 2025-10-03 13:08

import bank_accounts.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Compte', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_code', models.CharField(blank=True, max_length=40)),
                ('agency', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('iban_encrypted', bank_accounts.fields.EncryptedTextField(blank=True, null=True)),
                ('account_number_encrypted', bank_accounts.fields.EncryptedTextField(blank=True, null=True)),
                ('iban_normalized', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('masked_account', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('blocked', 'Blocked'), ('removed', 'Removed')], default='pending', max_length=16)),
                ('verification_metadata', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BankAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('fee', 'Fee'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
