# Generated by Django 5.2.6 on 2025-10-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('manage_personnel', '0005_delete_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', related_query_name='bank_account', to='manage_personnel.profile'),
        ),
    ]
