# Generated by Django 5.2.6 on 2025-10-03 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('manage_personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='manage_personnel.profile'),
        ),
        migrations.AddField(
            model_name='bankaudit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_accounts.bankaccount'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_personnel.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('profile', 'iban_normalized')},
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['external_reference'], name='bank_accoun_externa_83c11f_idx'),
        ),
    ]
