# Generated by Django 5.2.6 on 2025-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_alter_bankaccount_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(blank=True, default='MGA', max_length=8),
        ),
    ]
