# Generated by Django 5.2.6 on 2025-10-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='iban_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
